const oneMinuteMilliseconds = 60e3;

(async function main() {
    const firstVisitTime = await getResponse({ firstVisitTimeFor: location.hostname })
    const haveVisitedBeforeVeryRecently =
        firstVisitTime !== "null"
        &&
        ((new Date().valueOf() - new Date(firstVisitTime).valueOf()) > oneMinuteMilliseconds)

    if (haveVisitedBeforeVeryRecently) {
        return debugLog(`This site's most recent visit is not in the very recent past, so there's no need for a warning`)
    }

    displayWarning("Warning: You have not visited this site before or first visited it very recently, according to your browser history. Be aware of phishing attempts. This message was generated by the New Site Warning browser extension.")
})()

async function getResponse(message) {
    debugLog(`sending request: ${JSON.stringify(message)}`)

    return new Promise((resolve, reject) =>
        chrome.runtime.sendMessage(message, function (response) {
            if (!response) {
                debugLog(`no response, checking errors: ${JSON.stringify(chrome.runtime.lastError)}`)
                reject(chrome.runtime.lastError)
            }

            debugLog(`got response: ${response}`)
            resolve(response)
        })
    )
}

// TODO: Make this close-able
function displayWarning(message){
    const div = document.createElement('div')
    const p = document.createElement('p')
    div.setAttribute('style', 'all: unset; position: fixed; z-index: 10000000; background-color: #d97c7c; top: 10px; left: 10px; box-shadow: 3px')
    p.innerHTML = message
    div.appendChild(p)
    document.documentElement.appendChild(div)
}

function debugLog(...messages) {
    console.debug(`[New Site Warning browser extension] -`, ...messages)
}
